# Generated by Django 5.2.1 on 2025-06-04 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useform',
            name='name',
            field=models.CharField(default='none', max_length=100),
            preserve_default=False,
        ),
    ]
