# Generated by Django 5.1.7 on 2025-06-24 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_useform_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='useform',
            name='fear',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useform',
            name='pressure',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useform',
            name='urgency',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
